spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon_2025_test
    username: root
    password: 12345
  jpa:
    hibernate:
        ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: "server"

server:
  port: 8080

jwt:
  secret-key: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  access-token:
    expiration: 3600000  # 1 година
  refresh-token:
    expiration: 604800000
