spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon_2025_test
    username: root
    password: 12345
  jpa:
    hibernate:
        ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: "server"

