name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2

      - name: Build code
        run: |
          # Піднімаємо всі контейнери з docker-compose
          docker-compose -f docker-compose.yml up -d
          
          # Перевіряємо, що контейнери працюють
          docker ps
