name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build code
        run: |
          # Піднімаємо базу даних
          docker compose -f docker-compose.yml up -d db

          # Чекаємо, поки MySQL стане доступною
          echo "Waiting for MySQL to be ready..."
          until docker exec $(docker ps -q -f name=db) mysqladmin ping -uroot -p12345 --silent; do
            sleep 5
            echo "Still waiting..."
          done
          echo "MySQL is ready!"

          # Піднімаємо backend
          docker compose -f docker-compose.yml up -d backend

          # Піднімаємо frontend
          docker compose -f docker-compose.yml up -d client

          # Перевіряємо, що контейнери працюють
          docker ps
